# Generated by Django 2.2 on 2019-04-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(upload_to='media'),
        ),
    ]
